view.tree <- function(BRT,tree.num = 1){
  tree.tab <- gbm::pretty.gbm.tree(BRT,tree.num)
  build.newick <- function(TREE,node){
    node <- as.character(node)
    d1 <- as.character(TREE[node,3])
    d2 <- as.character(TREE[node,4])
    char <- BRT$var.names[as.numeric(node) + 1]
    split <- TREE[node,2]
    if(TREE[d1,3] == -1){
      val1 <- TREE[d1,2]
    }else{
      val1 <- build.newick(TREE,d1)[[1]]
      char <- c(char,build.newick(TREE,d1)[[2]])
      split <- c(split,build.newick(TREE,d1)[[3]])
    }
    if(TREE[d2,3] == -1){
      val2 <- TREE[d2,2]
    }else{
      val2 <- build.newick(TREE,d2)[[1]]
      char <- c(char,build.newick(TREE,d2)[[2]])
      split <- c(split,build.newick(TREE,d2)[[3]])
    }
    return(list(paste0("(",val1,",",val2,")"),
                char,
                split))
  }
  tree.newick <- build.newick(tree.tab,0)
  tree <- ape::read.tree(text = paste0(tree.newick[[1]],";"))
  plot(tree)
  labs <- paste0(tree.newick[[2]],"\nSplit = ",tree.newick[[3]])
  ape::nodelabels(labs,(length(tree$tip.label) + 1):(length(tree$tip.label) + tree$Nnode))
}

#' @title A function for viewing mini-tree created from Boosting algorithm
#' @description This function allows you visualize one of the trees generated by the boosting algorithm in the create.BRT function
#' @param BRT input BRT model of type gbm object
#' @param tree.num index number of mini-tree
#' @keywords BRT
#' @export
#' @examples
#' view.tree(BRT.model,tree.num = 3)


